# Generated by Django 3.0 on 2020-02-17 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cip_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='address',
            field=models.CharField(blank=True, help_text='Max 100 chars.', max_length=100, null=True, verbose_name='Address'),
        ),
        migrations.AddField(
            model_name='person',
            name='birth_place',
            field=models.CharField(choices=[('F', 'Female'), ('M', 'Male')], default=('F', 'Female'), help_text='Birth place', max_length=6, verbose_name='Birth place'),
        ),
        migrations.AddField(
            model_name='person',
            name='blood_types',
            field=models.CharField(choices=[('F', 'Female'), ('M', 'Male')], default=('F', 'Female'), help_text='Blood types', max_length=6, verbose_name='Blood types'),
        ),
        migrations.AddField(
            model_name='person',
            name='marital_status',
            field=models.CharField(choices=[('F', 'Female'), ('M', 'Male')], default=('F', 'Female'), help_text='Marital status', max_length=6, verbose_name='Marital status'),
        ),
        migrations.AlterField(
            model_name='person',
            name='identifier',
            field=models.CharField(help_text='Citizenship', max_length=11, unique=True, verbose_name='Identifier'),
        ),
    ]
