# Generated by Django 3.0.3 on 2020-02-05 19:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('USER_ID', models.IntegerField(unique=True, verbose_name='USER_ID')),
                ('CITIZENSHIP_NUMBER', models.CharField(max_length=11, unique=True, verbose_name='CITIZENSHIP_NUMBER')),
                ('GENDER', models.CharField(choices=[('F', 'Female'), ('M', 'Male')], max_length=6, verbose_name='GENDER')),
                ('BIRTHDAY', models.DateField(verbose_name='BIRTHDAY')),
                ('PHONE_NUMBER', models.CharField(max_length=17, validators=[django.core.validators.RegexValidator(message='Format: "+905304440044"', regex='^\\+(?:[0-9] ?){6,14}[0-9]$')])),
            ],
            options={
                'verbose_name': 'PERSON',
                'verbose_name_plural': 'PEOPLE',
                'ordering': ['USER_ID'],
            },
        ),
    ]
